"""Add selected_choice to assessment_question_responses

Revision ID: 3f080cd74b8d
Revises: 36c7744b9938
Create Date: 2025-08-12 23:54:31.475670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f080cd74b8d'
down_revision: Union[str, Sequence[str], None] = '36c7744b9938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_question_responses', sa.Column('selected_choice', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_question_responses', 'selected_choice')
    # ### end Alembic commands ###
