"""Add completion_eligible and eligibility_reason to AssessmentResults

Revision ID: 7bde0b60713f
Revises: 6203cc7dab49
Create Date: 2025-08-29 06:30:45.234861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bde0b60713f'
down_revision: Union[str, Sequence[str], None] = '6203cc7dab49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_results', sa.Column('completion_eligible', sa.Boolean(), nullable=True))
    op.add_column('assessment_results', sa.Column('eligibility_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_results', 'eligibility_reason')
    op.drop_column('assessment_results', 'completion_eligible')
    # ### end Alembic commands ###
