"""Add AssessmentQuestionResponse table

Revision ID: b46ee8a7e218
Revises: c9b4c17839cb
Create Date: 2025-08-05 15:33:52.152223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46ee8a7e218'
down_revision: Union[str, Sequence[str], None] = 'c9b4c17839cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
