// src/config/filipinoPhonetics.js

/**
 * Filipino words with phonetic transcription (Tagalog TTS-ready)
 * Grouped by usage: Basic words, verbs, course-specific additions
 * Avoids duplicates and improves readability
 */

export const filipinoPhonetics = {
  // ==========================
  // Basic Filipino words
  // ==========================
  'mga': 'muhng-ah',
  'ka': 'kah',
  'ko': 'koh',
  'mo': 'moh',
  'ng': 'n-g',
  'sa': 'sah',
  'ang': 'ahng',
  'kayo': 'kah-yoh',
  'tayo': 'tah-yoh',
  'ako': 'ah-koh',
  'siya': 'see-yah',
  'kami': 'kah-mee',
  'kana': 'kah-nah',
  'lang': 'lahng',
  'din': 'deen',
  'rin': 'reen',
  'naman': 'nah-mahn',
  'kasi': 'kah-see',
  'para': 'pah-rah',
  'kung': 'koong',
  'yung': 'yoong',
  'ano': 'ah-noh',
  'bakit': 'bah-keet',
  'paano': 'pah-ah-noh',
  'saan': 'sah-ahn',
  'sino': 'see-noh',
  'ito': 'ee-toh',
  'iyan': 'ee-yahn',
  'iyon': 'ee-yohn',
  'dito': 'dee-toh',
  'diyan': 'dee-yahn',
  'doon': 'doh-ohn',
  'alin': 'ah-lin',

  // ==========================
  // Common verbs / nouns
  // ==========================
  'ginagamit': 'gee-nah-gah-meet',
  'nakikita': 'nah-kee-kee-tah',
  'puwede': 'poo-weh-deh',
  'makina': 'mah-kee-nah',
  'tumutulong': 'too-moo-too-long',
  'gawain': 'gah-wah-een',
  'bahay': 'bah-high',
  'opisina': 'oh-pee-see-nah',
  'paaralan': 'pah-ah-rah-lahn',
  'pagsusulat': 'pahg-soo-soo-laht',
  'paggawa': 'pahg-gah-wah',
  'impormasyon': 'eem-por-mahs-yon',
  'manood': 'mah-noh-ohd',
  'makinig': 'mah-kee-neeg',
  'maglaro': 'mahg-lah-roh',
  'makipag': 'mah-kee-pahg',
  'malaking': 'mah-lah-keeng',
  'madaling': 'mah-dah-leeng',
  'dalhin': 'dahl-heen',
  'kahit': 'kah-heet',
  'maliit': 'mah-lee-eet',
  'gamitin': 'gah-mee-teen',
  'pisikal': 'pee-see-kahl',
  'parte': 'par-teh',
  'nahahawakan': 'nah-hah-hah-wah-kahn',
  'nagpapatakbo': 'nahg-pah-pah-tahk-boh',
  'magkasama': 'mahg-kah-sah-mah',
  'gumagana': 'goo-mah-gah-nah',
  'magamit': 'mah-gah-meet',
  'nagpapakita': 'nahg-pah-pah-kee-tah',
  'tunog': 'too-nohg',
  'boses': 'boh-ses',
  'makita': 'mah-kee-tah',
  'halimbawa': 'hah-leem-bah-wah',
  'piliin': 'pee-lee-een',
  'bawat': 'bah-waht',
  'hawakan': 'hah-wah-kahn',
  'hanapin': 'hah-nah-peen',
  'pindutin': 'peen-doo-teen',
  'hanggang': 'hahng-gahng',
  'lumabas': 'loo-mah-bahs',
  'papunta': 'pah-poon-tah',
  'nasa': 'nah-sah',
  'baba': 'bah-bah',
  'bukas': 'boo-kahs',
  'depende': 'deh-pen-deh',
  'galaw': 'gah-lahw',
  'pumili': 'poo-mee-lee',
  'magbukas': 'mahg-boo-kahs',
  'lumipat': 'loo-mee-paht',
  'magbura': 'mahg-boo-rah',
  'subukang': 'soo-boo-kahng',
  'simpleng': 'seem-plehng',
  'pangungusap': 'pah-ngoo-ngoo-sahp',
  'sundan': 'soon-dahn',
  'tamang': 'tah-mahng',
  'posisyon': 'poh-sees-yon',
  'kamay': 'kah-mai',
  'kaliwang': 'kah-lee-wahng',
  'mula': 'moo-lah',
  'rito': 'ree-toh',
  'maghanap': 'mahg-hah-nahp',
  'huwag': 'hoo-wahg',
  'basta': 'bahs-tah',
  'bunutin': 'boo-noo-teen',
  'maiwasan': 'mai-wah-sahn',
  'sira': 'see-rah',

  // ==========================
  // Course-specific  words
  // ==========================
  'trabaho': 'trah-bah-hoh',
  'naka-on': 'nah-kah-on',
  'mukhang': 'mook-hahng',
  'hakbang': 'hahk-bahng',
  'maayos': 'mah-ah-yohs',
  'lugar': 'loo-gahr',
  'paggamit': 'pahg-gah-meet',
  'balita': 'bah-lee-tah',
  'malinaw': 'mah-lee-nahw',
  'kapag': 'kah-pahg',
  'nag-PM': 'nahg-pee-em',
  'layunin': 'lah-yoo-neen',
  'tumulong': 'too-moo-long',
  'pera': 'peh-rah',
  'nakakasira': 'nah-kah-kah-see-rah',
  'protektahan': 'proh-tehk-tah-hahn',
  'kakilala': 'kah-kee-lah-lah',
  'alam': 'ah-lahm',
  'magnanakaw': 'mahg-nah-nah-kahw',
  'maibahagi': 'mah-ee-bah-hah-gee',
  'mag-isip': 'mahg-ee-seep',
  'makakasakit': 'mah-kah-kah-sah-kit',
  'komportable': 'kohm-por-tah-bleh',
  'panatilihing': 'pah-nah-tee-lee-heeng',
  'mag-log-out': 'mahg-log-owt',
  'maikling': 'mah-eek-leeng',
};

// ==========================
// Function to extend with course-specific phonetics
// ==========================
export const addCoursePhonetics = (newPhonetics) => {
  return { ...filipinoPhonetics, ...newPhonetics };
};

export default filipinoPhonetics;
